# Generated by Django 2.2.16 on 2022-07-03 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220703_1237'),
        ('reviews', '0002_auto_20220702_1836'),
    ]

    operations = [
    ]
